# Generated by Django 2.0.6 on 2020-06-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.SmallIntegerField()),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')])),
                ('phone', models.IntegerField(max_length=11)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'stu_system',
            },
        ),
    ]
